### PR TITLE
Builder with context (BuildContext)

### PR DESCRIPTION
**Pull request by LucienCorreia**

### CODE REVIEW

**Comment by itbrunoms** [comment]
BuilderWhenTrue is very expansive, use isTrue and isFalse.

Nice boy.

**Comment by LucienCorreia** [comment]
> BuilderWhenTrue is very expansive, use isTrue and isFalse.
> 
> Nice boy.

Done 👍🏽

**Review by juarezfranco — APPROVED** [review]

**Comment by juarezfranco** [comment]
#1

**Comment by juarezfranco** [comment]
Big thanks 👍🏽

**Pull request merged**
